let vimplug=expand('~/.vim/autoload/plug.vim')

if !filereadable(vimplug)
  if !executable("curl")
    echoerr "You have to install curl or first install vim-plug yourself!"
    execute "q!"
  endif
  echo "Installing Vim-Plug..."
  echo ""
  silent exec "!\curl -fLo " . vimplug . " --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(expand('~/.vim/plugged'))
Plug 'airblade/vim-gitgutter'
Plug 'kassio/neoterm'
Plug 'morhetz/gruvbox'
Plug 'sainnhe/gruvbox-material'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Language support
Plug 'sheerun/vim-polyglot'
Plug 'majutsushi/tagbar'
Plug 'dense-analysis/ale'
" Idris
Plug 'idris-hackers/idris-vim'
" Unison
Plug 'unisonweb/unison', { 'rtp': 'editor-support/vim' }
call plug#end()

set number
set tabstop=2
set shiftwidth=2
set expandtab

let &t_SI = "\<Esc>[5 q"
let &t_SR = "\<Esc>[3 q"
let &t_EI = "\<Esc>[1 q"

set background=dark
if &t_Co >= 256
  if has('termguicolors')
    set termguicolors
    let g:gruvbox_material_background = 'hard'
    let g:gruvbox_material_enable_bold = 1
    let g:gruvbox_material_enable_italic = 1
    let g:gruvbox_material_diagnostic_line_highlight = 1
    let g:gruvbox_material_palette = 'mix'
    colorscheme gruvbox-material
  else
    let g:gruvbox_contrast_dark = 'hard'
    colorscheme gruvbox
  endif
endif

let g:neoterm_default_mod='belowright'
let g:neoterm_size=16
let g:neoterm_autoscroll=1
nnoremap <leader><cr> :TREPLSendLine<cr>j
vnoremap <leader><cr> :TREPLSendSelection<cr>

let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline_skip_empty_sections = 1

let g:ale_completion_enabled = 1
